# MongoDB Atlas Configuration



# Opción 1: Usar la nueva base de datos proporcionada
spring.data.mongodb.uri=mongodb+srv://steveninsuasti:wPCMGUh0SeHXs3bM@cluster0.xaiammg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=vehicledb


# Server Configuration
server.port=8080

# Application Name
spring.application.name=vehicle-api

# Logging (opcional - para ver las queries de MongoDB)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
